### ISSUE TITLE
Complete Reference Guide to BibJSON

### ISSUE THREAD

**Issue by Marhc** [rufuspollock-okfn/bibjson#4]
Hi guys!

Where can I find a complete reference guide for BibJSON?

The site has broken links and does not cover many details like: 
What are the possible values ​​of the license type field? 

This is one of my personal doubts, for example.

**Comment by rufuspollock** [comment]
http://okfnlabs.org/bibjson/

**Comment by rufuspollock** [comment]
FIXED.
